# Debug Logging
debug: false
announcements:
  scheduled:
    everyMinute:
      enabled: false
      delay: 60
      message: |
        <green>This is an announcement that runs every 60 seconds.
        Because it is very long we wrote it over multiple lines in the config,
        but as you can see the message is displayed as one line in the chat!<newline><newline>
        We do love some space tho, right?
    every2min:
      enabled: false
      delay: 120
      message: <yellow>Hello this is an announcement that runs every 120 seconds
    tellTheTime:
      enabled: false
      delay: 10
      message: <gold>It is now <red><date_time:def> on day <date:"dd.MM.yyyy"> instead of <date:iso:1970-01-01><gold> o'clock, dear <player_name>
